[package]
name = "gamecast-services"
version = "0.1.0"
authors = ["Kurt Hartmann <extramileit@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
